- Cargo.toml
- benchmark/bench.ts
- benchmark/gradient.ts
- benchmark/house.ts
- example/gradient.js
- src/ctx.rs
- src/sk.rs
> feat: support gradient in fill/stroke style

- .github/workflows/CI.yaml
- .gitmodules
- scripts/build-skia.js
- skia-c/skia_c.cpp
```bash
Version References:
required from libdl.so.2:
0x09691a75 0x00 13 GLIBC_2.2.5
required from ld-linux-x86-64.so.2:
0x0d696913 0x00 11 GLIBC_2.3
required from libgcc_s.so.1:
0x09276060 0x00 15 GCC_4.2.0
0x0b792653 0x00 12 GCC_3.3
0x0b792650 0x00 05 GCC_3.0
required from libpthread.so.0:
0x06969192 0x00 09 GLIBC_2.12
0x09691972 0x00 07 GLIBC_2.3.2
0x09691a75 0x00 04 GLIBC_2.2.5
required from libm.so.6:
0x09691a75 0x00 03 GLIBC_2.2.5
required from libc.so.6:
0x06969194 0x00 18 GLIBC_2.14
0x09691974 0x00 17 GLIBC_2.3.4
0x0d696914 0x00 16 GLIBC_2.4
0x0d696916 0x00 14 GLIBC_2.6
0x06969198 0x00 10 GLIBC_2.18
0x09691972 0x00 08 GLIBC_2.3.2
0x06969197 0x00 06 GLIBC_2.17
0x09691a75 0x00 02 GLIBC_2.2.5
```
> feat: skia m89

- __test__/draw.spec.ts
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/ctx.rs
- src/sk.rs
This API is aligned with [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInPath), test cases are also included.
> feat: support isPointInPath

- rust-toolchain
- src/font.rs
Close https://github.com/Brooooooklyn/canvas/issues/214
Close https://github.com/Brooooooklyn/canvas/issues/213
> Font parse

- __test__/pathkit.spec.ts
- index.d.ts
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/path.rs
- src/sk.rs
TODO: add doc
See also: https://skia.org/docs/user/modules/pathkit/#dashon-off-phase
> feat: add PathKit.dash()

- .gitignore
- npm/icudtl/README.md
- npm/icudtl/package.json
- npm/icudtl/postinstall.js
- scripts/release-skia-binary.js
Close https://github.com/Brooooooklyn/canvas/issues/253
> ci: upload icudtl.dat for Windows

- index.js
- src/font.rs
Close https://github.com/Brooooooklyn/canvas/issues/345
> Strip famliy

- index.js
- src/ctx.rs
Close https://github.com/Brooooooklyn/canvas/issues/392
Close https://github.com/Brooooooklyn/canvas/issues/385
> fix: make methods on ctx configurable & writable

- README.md
The anime girl is under CC-BY 3.0, therefore you have to name the author.
In Building several steps seem to be missing?
> Example with copyrightinfo, Bulid with dependencies

- .github/workflows/docker.yml
- .github/workflows/skia.yaml
- Dockerfile
- aarch64.Dockerfile
- build.rs
- scripts/build-skia.js
Close https://github.com/Brooooooklyn/canvas/issues/507
> chore: static link libc++ on aarch64 linux gnu

- index.d.ts
Close https://github.com/Brooooooklyn/canvas/issues/499
> chore: remove const enum from .d.ts

- __test__/draw.spec.ts
- src/lib.rs
- Close https://github.com/Brooooooklyn/canvas/issues/498
> fix: the quality of toDataURL should between 0 and 1

- README-zh.md
- README.md
For `README-zh.md` changes, I just ran stuff through Google Translate (since I don't know Chinese), so it might be incorrect.
> docs: Clarify that AVIF is also supported in README

- __test__/draw.spec.ts
- src/ctx.rs
- Close https://github.com/Brooooooklyn/canvas/issues/526
> fix: segfault while drawing empty text

- index.d.ts
- index.js
- js-binding.js
- package.json
- scripts/debug-memory.mjs
- scripts/utils.js
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/ctx.rs
- src/lib.rs
- src/sk.rs
- yarn.lock
- Close https://github.com/Brooooooklyn/canvas/issues/412
- Close https://github.com/Brooooooklyn/canvas/issues/525
> fix: adjust Node.js external memory while creating Canvas

- src/lib.rs
- Close https://github.com/Brooooooklyn/canvas/issues/540
> fix: data url should be standard base64

- README.md
fixed the yarn command in readme
> docs: fix yarn command

- __test__/index.spec.ts
- index.d.ts
- index.js
- Close https://github.com/Brooooooklyn/canvas/issues/571
> fix: getTransform should return DOMMatrix

- Cargo.toml
- __test__/fixtures/broken.png
- __test__/image.spec.ts
- load-image.js
- src/image.rs
- Close https://github.com/Brooooooklyn/canvas/issues/641
> fix: reject if image is not supported

- __test__/echarts.spec.ts
- __test__/image.spec.ts
- index.d.ts
- src/image.rs
- Close https://github.com/Brooooooklyn/canvas/issues/572
> fix: set empty src to Image

- README.md
I didn't see any examples of the `loadImage` function in the English documentation, so I added them! Please let me know if you'd like for me to modify them or put them elsewhere. Thanks!
> Added a couple of examples of the `loadImage` function to README.md

- __test__/regression.spec.ts
- geometry.js
- Close https://github.com/Brooooooklyn/canvas/issues/781
> fix: DOMMatrix#transformPoint

- .github/workflows/CI.yaml
- __test__/regression.spec.ts
- build.rs
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/ctx.rs
- src/sk.rs
- Close https://github.com/Brooooooklyn/canvas/issues/784
> fix: isPointInPath/isPointInStroke should respect transform

- skia-c/skia_c.cpp
- Close https://github.com/Brooooooklyn/canvas/issues/716
> fix: memory leak while encoding png from Canvas

- .cargo/config.toml
- .taplo.toml
- Cargo.toml
- __test__/draw.spec.ts
- __test__/filter.spec.ts
- __test__/image-snapshot.ts
- __test__/image.spec.ts
- __test__/regression.spec.ts
- package.json
- skia-c/skia_c.cpp
- src/image.rs
- src/sk.rs
- yarn.lock
- Close https://github.com/Brooooooklyn/canvas/issues/867
> fix: image decode should be async

- src/image.rs
- Close https://github.com/Brooooooklyn/canvas/issues/882
> fix: image src is null after loaded

- geometry.js
> fix: `??` is error on node@10

- __test__/canvas-class.spec.ts
- src/ctx.rs
- src/lib.rs
Should solve https://github.com/Brooooooklyn/canvas/issues/713
> fix: Creating canvas with width or height of zero or less

- Cargo.toml
- src/image.rs
- Fix https://github.com/Brooooooklyn/canvas/issues/907
- Fix https://github.com/Brooooooklyn/canvas/issues/890
> fix: memory leak in Image/loadImage

- __test__/loadimage.spec.ts
- load-image.js
- Close https://github.com/Brooooooklyn/canvas/issues/919
> fix: loadImage convert ArrayBuffer issue

- src/ctx.rs
- src/lib.rs
in my last pr, the context is not set to svg
> fix: svg context

- __test__/regression.spec.ts
- src/ctx.rs
- Close https://github.com/Brooooooklyn/canvas/issues/848
> fix: panic when restore from scale(0,0) state

- __test__/regression.spec.ts
- src/ctx.rs
- src/sk.rs
- Close https://github.com/Brooooooklyn/canvas/issues/1000
> fix: don't panic if current ts is not able to invert when transform

- skia-c/skia_c.cpp
- Close https://github.com/Brooooooklyn/canvas/issues/997
> fix: draw canvas on canvas clip

- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/sk.rs
By add correct drop handle for SkPicture
- Close https://github.com/Brooooooklyn/canvas/issues/1004
> fix: memory leak in some blend mode

- src/ctx.rs
- src/sk.rs
- Close https://github.com/Brooooooklyn/canvas/issues/995
> fix: BlendMode::Plus should be mapped to "plus" globalCompositeOperation

- .github/workflows/CI.yaml
- Cargo.toml
- src/lib.rs
- Close https://github.com/Brooooooklyn/canvas/issues/1036
> chore: disable arch optimize on aarch64 linux

- Cargo.toml
- package.json
- yarn.lock
Ref: https://github.com/Brooooooklyn/canvas/issues/1073
> fix: putImageData doesn't work on Electron environment

- package.json
- src/ctx.rs
- yarn.lock
- Close https://github.com/Brooooooklyn/canvas/issues/1073
> fix: wrong data pointer to ImageData in Electron env

- .github/workflows/CI.yaml
- src/ctx.rs
- src/image.rs
- src/lib.rs
- Close https://github.com/Brooooooklyn/canvas/issues/1120
> fix: external memory usage adjustment mismatch
