- .gitignore
- example/image-data.js
- package.json
- yarn.lock
This simple example adds [pngjs](https://github.com/arian/pngjs) for JS side PNG decoding. I'm now trying to work on implementing `Image` for `ctx.drawImage`, from my understanding to the roadmap, `Image` should be usable with `decode` that loads binary image files, so pngjs can help bootstraping `Image` class before we have `decode` shipped.
Since I can't install `canvas` both on WSL and macOS Big Sur (neither yarn and npm works, https://github.com/Automattic/node-canvas/issues/1728), the `yarn.lock` is out of sync with `package.json` now. Is it a must to keep it as dev dependency?
> docs: add ImageData example

- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/sk.rs
With current CPU rendering backend, `flush` has no effect and is unnecessary to be used, since raster drawings are never deferred. Remove its binding reduces unused warning :) See Skia documentation: https://github.com/google/skia/blob/master/include/core/SkCanvas.h#L258
Also to my understanding, using CPU as the raster backend is the is better choice. Because we are not targeting real-time UI rendering, GPU doesn't take advantage here. CPU also scales better for server side cloud hosting.
> refactor: remove flush

- .eslintignore
- .gitignore
This PR fixes the `npm run lint` error, and ignores `.vscode` config files.
> chore: IDE config

- __test__/draw.spec.ts
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/ctx.rs
- src/sk.rs
This PR supports the `isPointInStroke` API. Quick notes:
* For hit test algorithm and the `0.3` magic number, see https://github.com/samizdatco/skia-canvas/blob/24a2269f8e09e75b467def686f03a61596a72367/native/src/context/mod.rs#L316
* For the underlying Skia API, see https://github.com/google/skia/blob/master/include/core/SkPaint.h#L431
* For test cases, see https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInStroke#examples
> feat: support isPointInStroke

- skia-c/skia_c.cpp
When `image.src` is set with buffer (whose content is encoded image), this buffer doesn't need to be copied. As long as the SkBitmap is created with that buffer, we keep the reference to the bitmap (whose content is the decoded RGBA bitmap).
However, this also leads to another problem: How to keep the reference to the original buffer? For now (and also previously) I haven't implemented the `let x = image.src` getter. To my understanding to do this, within the `image.src = buffer` setter, we need to keep the reference to the `buffer` JSValue using something like `let data = ctx.get::<JsBuffer>(0)?.into_ref()?` (found in [napi-rs docs](https://napi.rs/concepts/ref)). But if I want to assign this `data` to the `image` struct in Rust, I can't pass the Rust ownership check (this `data` can't …
> perf: disable image data copy

- __test__/image.spec.ts
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/ctx.rs
- src/image.rs
- src/sk.rs
* Fix image `src` getter, which returned `undefined` before.
* Support drawing image with shadow. The default mask blur filter can't generate shadow for images. The `SkImageFilters::DropShadowOnly` filter is used instead.
> fix: image src getter and shadow

- README-zh.md
- README.md
- __test__/pathkit.spec.ts
- index.d.ts
- index.js
Returns a String representing the fillType of this path. The values are either `nonzero` or `evenodd`.
See also: https://skia.org/docs/user/modules/pathkit/#getfilltypestring
> feat: add getFillTypeString() for PathKit

- .editorconfig
`.editorconfig` is only responsible for basic indentation and line wrapping, and does not format specific styles. For example, the specific formatting of JS uses prettier, and the formatting of C++ files uses [clang-format](https://clang.llvm.org/docs/ClangFormat.html).
> feat: add .editorconfig file

- npm/linux-arm64-gnu/install.js
- npm/linux-arm64-gnu/package.json
- npm/linux-arm64-musl/install.js
- npm/linux-arm64-musl/package.json
- npm/linux-x64-gnu/install.js
- npm/linux-x64-gnu/package.json
- npm/linux-x64-musl/install.js
- npm/linux-x64-musl/package.json
Currently, linux installs both glibc and musl binaries.
This PR adds the `install` script to prevent installing unused binaries, reducing the install size.
We originally thought this could be added to Node.js core and thus npm but [it was rejected](https://github.com/nodejs/node/pull/41338).
> Reduce install size for linux glibc/musl

- example/path-empty-line-to.js
- src/sk.rs
Fix the issue https://github.com/Brooooooklyn/canvas/issues/409
and + example
这里预期用和 skia-canvas 库用同一种方式解决吧
我也补上了用例 example/path-empty-line-to.js
验证是没问题的
> Fix the line to result of path empty case (issue: #409) + add the example

- src/sk.rs
Fixed the issue of empty path also happened at arc to + bezier to + quad to, and has test passed.
另外三个方法的空 Path 场景也修复完成了 也自测没问题了
```js
// arc to
ctx.beginPath()
ctx.arcTo(180, 90, 200, 30, 30)
ctx.arcTo(180, 130, 110, 130, 130)
ctx.stroke()
```
```js
// bézier curve to
ctx.beginPath()
ctx.bezierCurveTo(40, 20, 10, 10, 30, 30)
ctx.bezierCurveTo(120, 160, 180, 10, 220, 140)
ctx.stroke()
```
```js
// quadratic curve to
ctx.beginPath()
ctx.quadraticCurveTo(10, 10, 20, 110)
ctx.quadraticCurveTo(230, 150, 250, 20)
ctx.stroke()
```
> fix: Fix the issue of arc to + bezier to + quad to at empty path case

- example/anime-girl-quality.js
- index.js
- src/lib.rs
尝试修复了一下 `.encode(type, quality)` 方法的 quality 默认值的问题 [https://github.com/Brooooooklyn/canvas/issues/407](https://github.com/Brooooooklyn/canvas/issues/407)
以及关联的几个方法 确认测试通过
可看下是否是预期之内的方式
> Try to fix the encode method default quality issue

- npm/linux-arm64-gnu/install.js
- npm/linux-arm64-musl/install.js
- npm/linux-x64-gnu/install.js
- npm/linux-x64-musl/install.js
https://nodejs.org/api/process.html#processreport
Version | Changes
-- | --
v13.12.0, v12.17.0 | This API is no longer experimental.
v11.8.0 | Added in: v11.8.0
cc @styfle
> chore: note to improve, libc version detection only supports Node.js >= v13.12.0 or v12.17.0

- benchmark/gradient.ts
- benchmark/house.ts
~~`.async`~~ **The async property has been deprecated** and will be removed in a future release of [`skia-canvas`](https://github.com/samizdatco/skia-canvas)
> fix: skia async prop deprecated in future release

- __test__/loadimage.spec.ts
- index.d.ts
- load-image.js
Additions to the #483
This PR adds support for `internal.Readable` streams as image source and ability to set `alt` via `loadImage`.
> feat(loadImage): add stream and alt support

- index.d.ts
Without this reference, DOM types such as `CanvasRenderingContext2D` will appear as `unresolved` / `any` unless you include the DOM lib in your own tsconfig.json file.
This fixes #464
> typings: add dom lib reference

- load-image.js
This PR fixes a bug in the `loadImage` redirect handler. The current implementation throws an error because `res.headers.location` is passed as a string to the handler, which results in `url.protocol` being `undefined`.
> fix(loadImage): redirect handler

- load-image.js
```bash
Error: socket hang up
at connResetException (node:internal/errors:692:14)
at Socket.socketOnEnd (node:_http_client:478:23)
at Socket.emit (node:events:539:35)
at endReadableNT (node:internal/streams/readable:1345:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ClientRequest instance at:
at Socket.socketOnEnd (node:_http_client:478:9)
at Socket.emit (node:events:539:35)
at endReadableNT (node:internal/streams/readable:1345:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
code: 'ECONNRESET'
}
```
> fix: error listening to req

- index.d.ts
In TypeScript, `/// <reference` tags affect the whole environment, meaning that if a single dependency makes use of the tag, the user's global environment would be polluted with these types. The correct way of importing DOM types is by specifying them in the `lib` property of `tsconfig.json`, [which this library already does](https://github.com/Brooooooklyn/canvas/blob/9c505e2530a6c526b1e338a785115edeeafae267/tsconfig.json#L13).
<details>
<summary>Without the fix, using window in a project that installed @napi-rs/canvas that doesn't use DOM types</summary>
</details>
<details>
<summary>After the change, global scope is no longer polluted with DOM types for the project that installed this lib</summary>
</details>
Some examples of global pollution can be found at …
> fix(types): do not use `reference` tags

- src/ctx.rs
- src/error.rs
- src/global_fonts.rs
- src/lib.rs
- src/svg.rs
- Close https://github.com/Brooooooklyn/canvas/issues/432
> fix: resize canvas should clear the context

- index.js
In jest testing environments:
- Modules are `require/import` multiple times and not cached.
- However, looks like native objects ARE being cached.
- This caused `Object.defineProperty` in the require script to run multiple times and throws on the same native object(namely `GlobalFonts`).
> fix: multiple define on cached native object in jest

- load-image.js
Changed `loadImage` to use fs promises api instead of the sync api
> refactor(loadImage): use promise version of existsSync

- __test__/canvas-class.spec.ts
- index.d.ts
- src/lib.rs
- Close https://github.com/Brooooooklyn/canvas/issues/588
> fix: missing canvas property on Context2D

- __test__/canvas-class.spec.ts
- index.js
fixes #630 
`constructor` check might not be possible since we have `CanvasElement` and `SVGCanvas`. Most of the times, `instanceof` should be enough.
> fix: canvas instance check

- skia-c/skia_c.cpp
- Close https://github.com/Brooooooklyn/canvas/issues/716
- Close https://github.com/Brooooooklyn/canvas/issues/771
- Close https://github.com/Brooooooklyn/canvas/issues/735
> fix: memory leak in Canvas encode

- __test__/image.spec.ts
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/error.rs
- src/image.rs
- src/sk.rs
- Close https://github.com/Brooooooklyn/canvas/issues/832
> fix: trigger onerror while svg image is invalid

- load-image.js
Fixes #865, see the description of the original issue there.
This PR does two things:
- One, this wraps the `http.get()`/`https.get()` callback in `loadImage()` in a `try...catch` block so that exceptions are properly handled and passed to callers instead of crashing the Node process.
- Two, this passes `url.origin` as the second parameter to `new URL()` to ensure that "relative" redirects (where the `location` header is something like `/some/resource.jpg` instead of `https://site.com/some/resource.jpg`) do not cause the constructor to throw an exception.
Redirects to another domain (for example, a `location` header to `https://other.com` from the origin `https://site.com`) are not affected by adding the second parameter. Only relative URLs are affected -- the kind that currently cause …
> fix: handle relative and invalid URLs in redirects when passing URL to loadImage()

- example/image.js
- src/image.rs
https://github.com/Brooooooklyn/canvas/issues/891
> fix: adjust the order of onload calls

- load-image.js
- Close https://github.com/Brooooooklyn/canvas/issues/890
> fix: loadImage memleak and performance issue

- __test__/draw.spec.ts
- Close https://github.com/Brooooooklyn/canvas/issues/899
> test: add test for measureText to escape texts

- __test__/svg-canvas.spec.ts
- src/lib.rs
- src/path.rs
> fix(SvgCanvas): allow canvas size modification

- Cargo.toml
- build.rs
- src/image.rs
There 2 leak points in the `Image` class.
1. The `Env::create_reference` was wrong in NAPI-RS, related pr: https://github.com/napi-rs/napi-rs/pull/2347, change to the `Ref::new` can resolve it.
2. The `PromiseRaw::catch` callback was leaked, it cause the whole `Image` objects not be GCed, it was fixed in https://github.com/napi-rs/napi-rs/pull/2348
> fix: memory leak in Image

- src/image.rs
after clearing, the `bitmap` should be cleared, and the `width` and `height` should be reset to the initial values.
> feat: after clearing, the `bitmap` should be cleared, and the `width` and `height` should be reset to the initial values.

- npm/win32-x64-msvc/package.json
- Close https://github.com/Brooooooklyn/canvas/issues/952
> fix: missing icudtl.dat on Windows

- __test__/loadimage.spec.ts
- load-image.js
- Close https://github.com/Brooooooklyn/canvas/issues/956
> fix: loadImage should handle file URL

- .github/workflows/CI.yaml
- __test__/regression.spec.ts
- build.rs
- package.json
- rust-toolchain.toml
- skia-c/skia_c.cpp
- src/ctx.rs
- src/filter.rs
- src/lib.rs
- src/sk.rs
- src/svg.rs
- yarn.lock
- Close https://github.com/Brooooooklyn/canvas/issues/973
> fix: double free in putImageData

- .github/workflows/CI.yaml
- build.rs
- skia-c/skia_c.cpp
- skia-c/skia_c.hpp
- src/ctx.rs
- src/sk.rs
- Close https://github.com/Brooooooklyn/canvas/issues/972
> perf: avoid memcpy while drawing canvas on canvas

- skia-c/skia_c.cpp
```js
const { loadImage } = require('./index.js');
(async () => {
for (let i = 1; i <= 10000; i++) {
await loadImage('./docs/imgs/boolean-operations.svg');
console.log(i, process.memoryUsage().rss);
}
})();
```
Current:
```
[...]
9998 7788466176
9999 7789252608
10000 7790039040
```
With patch:
```
[...]
9998 420646912
9999 420646912
10000 420646912
```
> fix: memory leak when creating bitmap from svg

- index.d.ts
- tsconfig.json
This allows code that depends on @napi-rs/canvas to not include DOM types while typechecking
> chore: include needed dom types instead of relying on bundled DOM lib
